# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_pb2 as service__pb2


class ServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.add = channel.unary_unary(
                '/service.Server/add',
                request_serializer=service__pb2.addMsg.SerializeToString,
                response_deserializer=service__pb2.addReply.FromString,
                )
        self.dotproduct = channel.unary_unary(
                '/service.Server/dotproduct',
                request_serializer=service__pb2.dotProductMsg.SerializeToString,
                response_deserializer=service__pb2.dotProductReply.FromString,
                )
        self.rawimage = channel.unary_unary(
                '/service.Server/rawimage',
                request_serializer=service__pb2.rawImageMsg.SerializeToString,
                response_deserializer=service__pb2.imageReply.FromString,
                )
        self.jsonimage = channel.unary_unary(
                '/service.Server/jsonimage',
                request_serializer=service__pb2.jsonImageMsg.SerializeToString,
                response_deserializer=service__pb2.imageReply.FromString,
                )


class ServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def add(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def dotproduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def rawimage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def jsonimage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'add': grpc.unary_unary_rpc_method_handler(
                    servicer.add,
                    request_deserializer=service__pb2.addMsg.FromString,
                    response_serializer=service__pb2.addReply.SerializeToString,
            ),
            'dotproduct': grpc.unary_unary_rpc_method_handler(
                    servicer.dotproduct,
                    request_deserializer=service__pb2.dotProductMsg.FromString,
                    response_serializer=service__pb2.dotProductReply.SerializeToString,
            ),
            'rawimage': grpc.unary_unary_rpc_method_handler(
                    servicer.rawimage,
                    request_deserializer=service__pb2.rawImageMsg.FromString,
                    response_serializer=service__pb2.imageReply.SerializeToString,
            ),
            'jsonimage': grpc.unary_unary_rpc_method_handler(
                    servicer.jsonimage,
                    request_deserializer=service__pb2.jsonImageMsg.FromString,
                    response_serializer=service__pb2.imageReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'service.Server', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Server(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/service.Server/add',
            service__pb2.addMsg.SerializeToString,
            service__pb2.addReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def dotproduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/service.Server/dotproduct',
            service__pb2.dotProductMsg.SerializeToString,
            service__pb2.dotProductReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def rawimage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/service.Server/rawimage',
            service__pb2.rawImageMsg.SerializeToString,
            service__pb2.imageReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def jsonimage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/service.Server/jsonimage',
            service__pb2.jsonImageMsg.SerializeToString,
            service__pb2.imageReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
